version: '3'
services:
  flask_app:
    environment:
      - FLASK_ENV=production
    ports:
      - "80:80"
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    depends_on:
      - flask_app
  prometheus:
    image: prom/prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus:/etc/prometheus
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
    depends_on:
      - flask_app
  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SERVER_ROOT_URL=http://localhost:3000
    depends_on:
      - prometheus
